actividad v21

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,57 +26,7 @@ jobs:
       - name: Ejecutar Checkstyle
         run: ./gradlew :app:check
 
-  coverage-check:
-    name: Test Coverage Check
-    runs-on: ubuntu-latest
-    needs: [ lint ] # Se ejecuta después del linting
-    steps:
-      - name: Checkout del código
-        uses: actions/checkout@v4
 
-      - name: Configurar JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'temurin'
-
-      - name: Dar permisos de ejecución a Gradlew
-        run: chmod +x ./gradlew
-
-      - name: Generar reporte de cobertura con JaCoCo
-        # Este comando ejecuta los tests y luego genera el reporte de JaCoCo
-        run: ./gradlew :app:test :app:jacocoTestReport
-
-      - name: Extraer el porcentaje de cobertura
-        id: jacoco
-        run: |
-          # Extraemos el porcentaje de instrucciones cubiertas del reporte XML
-          coverage_percentage=$(cat app/build/reports/jacoco/test/jacocoTestReport.xml | awk -F'"' '/<counter type="INSTRUCTION"/{print int($14/($12+$14)*100)}')
-          echo "Coverage Percentage: $coverage_percentage%"
-          # Guardamos el valor como un "output" del paso
-          echo "coverage_percentage=$coverage_percentage" >> $GITHUB_OUTPUT
-
-      - name: Validar umbral de cobertura (mínimo 80%)
-        run: |
-          threshold=80
-          coverage=${{ steps.jacoco.outputs.coverage_percentage }}
-          
-          echo "El umbral requerido es ${threshold}%."
-          echo "La cobertura actual es ${coverage}%."
-          
-          if (( 70 < threshold )); then
-            echo "Error: La cobertura de código de ${coverage}% está por debajo del umbral requerido de ${threshold}%."
-            exit 1
-          else
-            echo "Éxito: La cobertura de código cumple con el umbral."
-          fi
-
-      - name: Subir reporte de cobertura de JaCoCo
-        if: always() # Se ejecuta siempre, incluso si el paso anterior falla
-        uses: actions/upload-artifact@v4
-        with:
-          name: jacoco-coverage-report
-          path: app/build/reports/jacoco/
 
   build-and-test:
     runs-on: ubuntu-latest
@@ -125,3 +75,55 @@ jobs:
           path: app/build/test-results/test/
 
 
+
+  coverage-check:
+    name: Test Coverage Check
+    runs-on: ubuntu-latest
+    needs: [ lint ] # Se ejecuta después del linting
+    steps:
+      - name: Checkout del código
+        uses: actions/checkout@v4
+
+      - name: Configurar JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+
+      - name: Dar permisos de ejecución a Gradlew
+        run: chmod +x ./gradlew
+
+      - name: Generar reporte de cobertura con JaCoCo
+        # Este comando ejecuta los tests y luego genera el reporte de JaCoCo
+        run: ./gradlew :app:test :app:jacocoTestReport
+
+      - name: Extraer el porcentaje de cobertura
+        id: jacoco
+        run: |
+          # Extraemos el porcentaje de instrucciones cubiertas del reporte XML
+          coverage_percentage=$(cat app/build/reports/jacoco/test/jacocoTestReport.xml | awk -F'"' '/<counter type="INSTRUCTION"/{print int($14/($12+$14)*100)}')
+          echo "Coverage Percentage: $coverage_percentage%"
+          # Guardamos el valor como un "output" del paso
+          echo "coverage_percentage=$coverage_percentage" >> $GITHUB_OUTPUT
+
+      - name: Validar umbral de cobertura (mínimo 80%)
+        run: |
+          threshold=80
+          coverage=${{ steps.jacoco.outputs.coverage_percentage }}
+
+          echo "El umbral requerido es ${threshold}%."
+          echo "La cobertura actual es ${coverage}%."
+
+          if (( coverage < threshold )); then
+            echo "Error: La cobertura de código de ${coverage}% está por debajo del umbral requerido de ${threshold}%."
+            exit 1
+          else
+            echo "Éxito: La cobertura de código cumple con el umbral."
+          fi
+
+      - name: Subir reporte de cobertura de JaCoCo
+        if: always() # Se ejecuta siempre, incluso si el paso anterior falla
+        uses: actions/upload-artifact@v4
+        with:
+          name: jacoco-coverage-report
+          path: app/build/reports/jacoco/
